apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-blue
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
      version: blue
  template:
    metadata:
      labels:
        app: backend
        version: blue
    spec:
      containers:
        - name: backend
          image: amaonbooks.azurecr.io/ecommerce-backend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          command: ["sh", "-c", "sleep 30 && java -jar *.jar"]
          env:
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:mysql://mysql:3306/ecommerce"
            - name: SPRING_DATASOURCE_USERNAME
              value: "root"
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secrets
                  key: MYSQL_ROOT_PASSWORD